### ISSUE TITLE
[Packer] Bad timing on image creation (probably too early)

### ISSUE THREAD

**Issue by Nainterceptor** [scaleway/image-tools#209]
Hello,

Firstly, thanks for the packer builder 👍
I'm playing with Packer & Scaleway, I've a simple issue (related to ticket _LELQ_, where support ask me to report issue here) : My script end too early, the last action has not ended before image creation

---
What I do :
* Run shell provisionner to setup ansible & python
* Run Ansible script (and upload playbook_dir)

Last action in my Ansible script is a _template_

In this case, copied file with template is empty, and take 0b.

If I build with -debug option, it's working because of timing change
When I add a sleep (from Ansible _pause_) or in another shell provisionner, it's working

So I think that something happen like too early image creation, something is maybe too fast.

---

### packer.json
```json
{
  "variables": {
    // ...
  },
  "builders": [
    //...
  ],
  "provisioners": [
    {
      "type": "shell",
      "inline": [
        "apt update && apt install gnupg -y",
        "echo 'deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main' | tee -a /etc/apt/sources.list.d/ansible.list",
        "apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367",
        "apt update",
        "apt install ansible python-netaddr python-pip -y"
      ]
    },
    {
      "type": "ansible-local",
      "playbook_dir": "./ansible",
      "playbook_file": "./ansible/ansible.yml"
    }
  ]
}
```

### ansible.yml
```yml
---
- hosts: localhost
  tasks:
    - name: "Upgrade package manager"
      apt: upgrade=dist

    - name: "Install list of packages"
      apt: name={{item}} state=present
      with_items:
        - curl
        - unzip
        - jq
        - supervisor

# Doing a lot of other things

    - name: "Copy a template"
      template:
        src: "./template.j2"
        dest: "/var/foo"
        mode: 0744

# Without the following pause, my copied template is 0 bytes length
    - name: "Pause few seconds to fix Scaleway packing"
      pause:
        seconds: 30
```

Thanks for your help (I have fixed as previous but it's not the right solution :))

Gaël
